# Generated by Django 4.2.4 on 2023-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Content', '0003_alter_comment_content_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
